---
- name: add group "nginx"
  group: 
    name: nginx

- name: add user "nginx"
  user: 
    name: nginx 
    group: nginx 
    shell: /sbin/nologin 
    createhome: no
  become: True
  become_method: sudo

- name: copy /nginx-1.10.2.tar.gz to agent server
  copy: src=/documents/devops/nginx-1.10.2.tar.gz dest=/documents/devops/nginx-1.10.2.tar.gz

- name: Extract archive
  command: chdir=/documents/devops /bin/tar xvzf nginx-1.10.2.tar.gz -C /opt creates=/opt/nginx-1.10.2

- name: Install gcc for compile
  yum:
    name: gcc
    state: present

- name: Install pcre for nginx
  yum:
    name: pcre
    state: present

- name: Config nginx
  command: chdir=/opt/nginx-1.10.2 ./configure --user=nginx --group=nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --with-select_module --with-poll_module --with-file-aio --with-ipv6 --with-http_ssl_module  --with-http_realip_module --with-http_addition_module --with-http_xslt_module --with-http_image_filter_module --with-http_geoip_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_auth_request_module --with-http_random_index_module --with-http_secure_link_module --with-http_degradation_module --with-http_stub_status_module --with-http_perl_module --with-mail --with-mail_ssl_module --with-cpp_test_module  --with-cpu-opt=CPU --with-pcre  --with-pcre-jit  --with-md5-asm  --with-sha1-asm  --with-zlib-asm=CPU --with-libatomic --with-debug --with-ld-opt="-Wl,-E"

- name: make install nginx
  make: chdir=/opt/devops/nrpe-nrpe-2-15 target=install

- name: start nginx
  command: /usr/sbin/nginx -c /etc/nginx/nginx.conf
