---
- name: Stop tomcat server
  command: service tomcat stop

- name: Make sure the site is exist in server.xml
  blockinfile: 
    dest: /usr/share/tomcat/conf/server.xml
    insertbefore: '</Engine>'
    content: |
      <Host name="{{ server_hostname }}" appBase="/sites/tomcat" unpackWARs="true" autoDeploy="true">
        <Context path="" docBase="sagiller" reloadable="true" />
      </Host>

- name: remove old version package direcoty
  file: path=/usr/share/tomcat/webapps/sagiller/ state=absent

- name: remove old version package
  file: path=/usr/share/tomcat/webapps/sagiller.war state=absent

- name: Copy war file to webapps directory and restart tomcat
  copy: src={{ sagiller_war_path }}/sagiller.war dest={{ tomcat_webapps_path }}/sagiller.war

- name: start tomcat server
  service: name=tomcat state=started

- name: Copy nginx configuration for tomcat
  template: 
    src: domain.conf 
    dest: /etc/nginx/conf.d/tomcat.conf
  vars:
    hostname: "{{ tomcat_hostname }}"
    http_port: "{{ tomcat_http_port }}"
  notify: restart nginx

- name: Copy nginx configuration for jenkins
  template: 
    src: domain.conf 
    dest: /etc/nginx/conf.d/jenkins.conf
  vars:
    hostname: "{{ jenkins_hostname }}"
    http_port: "{{ jenkins_http_port }}"
  notify: restart nginx

- name: Copy nginx configuration for {{ server_hostname }}
  template: 
    src: domain.conf 
    dest: /etc/nginx/conf.d/"{{ server_hostname }}".conf
  vars:
    hostname: "{{ server_hostname }}"
    http_port: "{{ tomcat_http_port }}"
  notify: restart nginx