---
- name: Stop tomcat server
  command: service tomcat stop

- name: remove old version package direcoty
  file: path=/usr/share/tomcat/webapps/sagiller/ state=absent

- name: remove old version package
  file: path=/usr/share/tomcat/webapps/sagiller.war state=absent

- name: Copy war file to webapps directory
  copy: src={{ sagiller_war_path }}/sagiller.war dest=/usr/share/tomcat/webapps/sagiller.war

- name: start tomcat server
  #command: service tomcat start
  notify: restart tomcat

- name: Copy nginx configuration for tomcat
  template: 
    src: domain.conf 
    dest: /etc/nginx/conf.d/tomcat.conf
  vars:
    hostname: "{{ tomcat_hostname }}"
    http_port: "{{ tomcat_http_port }}"
  notify: restart nginx

- name: Copy nginx configuration for jenkins
  template: 
    src: domain.conf 
    dest: /etc/nginx/conf.d/jenkins.conf
  vars:
    hostname: "{{ jenkins_hostname }}"
    http_port: "{{ jenkins_http_port }}"
  notify: restart nginx