- name: Stop tomcat server
  command: service tomcat stop

- name: remove old version package direcoty
  file: path=/usr/share/tomcat/webapps/UniversityTool/ state=absent

- name: remove old version package
  file: path=/usr/share/tomcat/webapps/UniversityTool.war state=absent
- name: Copy war file to webapps directory
  copy: src=/var/lib/jenkins/workspace/pipeline_test/target/UniversityTool.war dest=/usr/share/tomcat/webapps/UniversityTool.war

- name: workaround about the exception of UnknownHostException wadcnhgh02 corp capgemini com
  command: sed -i '/wadcnhgh02.corp.capgemini.com/d' /etc/hosts

- name: workaround about the exception of UnknownHostException wadcnhgh02 corp capgemini com
  command: sed -i '$a\10.61.208.38    wadcnhgh02.corp.capgemini.com   unkownhost' /etc/hosts

- name: start tomcat server
  command: service tomcat start
