- name: Stop tomcat server
  command: service tomcat stop

- name: remove old version package direcoty
  file: path=/usr/share/tomcat/webapps/sagiller/ state=absent

- name: remove old version package
  file: path=/usr/share/tomcat/webapps/sagiller.war state=absent

- name: Copy war file to webapps directory
  copy: src={{ sagiller_war_path }}/sagiller.war dest=/usr/share/tomcat/webapps/sagiller.war

- name: start tomcat server
  command: service tomcat start
