---
#playbook for test
- name: invoke role init
  hosts: init
  remote_user: root
  roles:
     - initserver

- name: invoke role java
  hosts: centos
  remote_user: sagiller
  become: yes
  become_method: sudo
  roles:
     - java
       when: "ansible_os_family == 'RedHat'"
       java_packages:
         - java-1.8.0-openjdk

- name: invoke role maven
  hosts: centos
  remote_user: sagiller
  become: yes
  become_method: sudo
  roles:
     - maven

- name: invoke role jenkins
  hosts: centos
  remote_user: sagiller
  become: yes
  become_method: sudo
  roles:
     - jenkins

- name: invoke role nginx
  hosts: centos
  remote_user: sagiller
  become: yes
  become_method: sudo
  roles:
     - nginx     

- name: invoke role tomcat
  hosts: centos
  remote_user: sagiller
  become: yes
  become_method: sudo
  roles:
     - tomcat     
