---
# This role is to install and configura java environment.
- name: Install Java openjdk 1.8
  yum:
    name: java-1.8.0-openjdk
    state: present

- name: Config java environment parameters
  lineinfile:
    dest: /etc/profile
    state: present
    line: 'export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk'
- lineinfile:
    dest: /etc/profile
    state: present
    line: 'export JRE_HOME=/usr/lib/jvm/java-1.8.0-openjdk/jre'
- lineinfile:
    dest: /etc/profile
    state: present
    line: 'export PATH=$PATH:$JAVA_HOME/bin:$JRE_HOME/bin'
- lineinfile:
    dest: /etc/profile
    state: present
    line: 'export CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar:$JRE_HOME/lib'

- name: Source /etc/profile
  raw: source /etc/profile