---
- name: Ensure Java is installed.
  package: "name={{ item }} state=installed"
  with_items: "{{ java_packages }}"

- name: copy apache-tomcat-8.5.9.tar.gz to agent server
  copy: src=/documents/devops/jdk-8u111-linux-x64.tar.gz dest=/documents/devops/jdk-8u111-linux-x64.tar.gz 

- name: Extract archive
  command: chdir=/documents/devops /bin/tar xvf jdk-8u111-linux-x64.tar.gz -C /opt creates={{ java_home }}

- name: Config java environment parameters
  lineinfile:
    dest: /etc/profile
    state: present
    line: 'export JAVA_HOME={{ java_home }}'
- lineinfile:
    dest: /etc/profile
    state: present
    line: 'export JRE_HOME={{ java_home }}/jre'
- lineinfile:
    dest: /etc/profile
    state: present
    line: 'export PATH=$PATH:$JAVA_HOME/bin:$JRE_HOME/bin'
- lineinfile:
    dest: /etc/profile
    state: present
    line: 'export CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar:$JRE_HOME/lib'

- name: Source /etc/profile
  raw: source /etc/profile

