---
# This role is to init server status with common tools and configs for centos7

# - name: Download jenkins repo
#   command:
#     wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo

# - name: Download jenkins repo
#   get_url:
#     url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
#     dest: /etc/yum.repos.d/jenkins.repo

# - name: Import jenkins verification key
#   command:
#     rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key

# - name: Install Jenkins
#   yum:
#     name: jenkins
#     state: present 
- name: copy Jenkins rpm package
  copy: src=/documents/devops/jenkins-2.32.1-1.1.noarch.rpm dest=/documents/devops/jenkins-2.32.1-1.1.noarch.rpm 

- name: Install Jenkins
  command: rpm –ih /documents/devops/jenkins-2.7.4-1.1.noarch.rpm 		
